# Site settings
title: Miguel Cardona | Designer & Illustrator
email: hello@miguelcardona.com
description: Miguel Cardona is a Designer, Illustrator and Photographer living in San Francisco, CA. He currently is the Lead Designer at imgix. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://miguelcardona.com" # the base hostname & protocol for your site
twitter_username: miggi
github_username:  gitmiggi

# Build settings
markdown: kramdown
